name = "human-observation"
main = "src/worker.js"
compatibility_date = "2024-07-20"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "human"
database_id = "eff3b8bd-67e5-4c58-93f6-547a7e4af516"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "human"
